steps:
 # I Guess not needed with newer versions of docker with cache from
  # Build the container image
  # - name: "gcr.io/cloud-builders/docker"
  #   id: "Pull"
  #   entrypoint: "bash"
  #   args:
  #     [
  #       "-c",
  #       "docker pull $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$BRANCH_NAME-latest || exit 0",
  #     ]
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -t ${_IMAGE}:latest -t ${_IMAGE}:$BRANCH_NAME --build-arg SHOPIFY_API_KEY=$$SHOPIFY_API_KEY --cache-from ${_IMAGE}:latest --cache-from ${_IMAGE}:$BRANCH_NAME .",
      ]
    secretEnv: ["SHOPIFY_API_KEY"]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      [
        "push",
        "${_IMAGE}",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Update service"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "$_SERVICE_NAME"
      - "--image"
      - "${_IMAGE}"
      - "--region"
      - "$_DEPLOY_REGION"
      - "--labels=revision-id=$REVISION_ID,gcb-build-id=$BUILD_ID,branch=$BRANCH_NAME"
      - "--quiet"
images:
  - "us-docker.pkg.dev/$PROJECT_ID/$_GCR_HOSTNAME/$REPO_NAME/$_SERVICE_NAME"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: shopify-app-name
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  # For Artifact Registry:
  _IMAGE: us-docker.pkg.dev/${PROJECT_ID}/${_GCR_HOSTNAME}/${REPO_NAME}/${_SERVICE_NAME}
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/shopify_api_key/versions/latest
      env: "SHOPIFY_API_KEY"
